/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rps5r;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class r5r extends javax.swing.JFrame {

    /**
     * Creates new form r5r
     */
    public r5r() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 160, 95, 32));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 157, 97, 35));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 238, 95, 37));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 238, 96, 37));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 321, 95, 37));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 321, 97, 37));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 404, 95, 37));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 404, 97, 37));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 487, 95, 37));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 487, 97, 37));

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("FIGHT!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 162, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("ROUND 1:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 157, 117, 32));

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("FIGHT!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 245, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("ROUND 2:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 241, 99, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("FIGHT!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 321, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("ROUND 3:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 324, 99, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("ROUND 4:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 407, 99, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("ROUND 5:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 490, 99, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("FIGHT!");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 411, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("FIGHT!");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 494, -1, -1));

        jLabel6.setFont(new java.awt.Font("STCaiyun", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("PLAYER 2:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 125, -1, -1));

        jLabel7.setFont(new java.awt.Font("STCaiyun", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("PLAYER 1:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 125, -1, -1));

        jTextField11.setBackground(new java.awt.Color(204, 0, 0));
        jTextField11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(0, 0, 0));
        jTextField11.setText("3");
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 88, 30, -1));

        jTextField12.setBackground(new java.awt.Color(204, 0, 0));
        jTextField12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(0, 0, 0));
        jTextField12.setText("3");
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 88, 30, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("LIVES:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 99, 51, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("LIVES:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 95, 51, -1));

        jLabel10.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 51));
        jLabel10.setText("[1] --- ROCK");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 25, 243, -1));

        jLabel11.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 255, 51));
        jLabel11.setText("[2] --- PAPER");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 25, 264, -1));

        jLabel12.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 255, 51));
        jLabel12.setText("[3] --- SCISSOR");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 25, 264, -1));
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 163, 116, -1));
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 245, 116, -1));
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 328, 116, -1));

        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 411, 116, -1));

        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 494, 116, -1));

        jLabel13.setFont(new java.awt.Font("STCaiyun", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("RESULT;");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, -1, -1));

        jButton6.setBackground(new java.awt.Color(204, 0, 204));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("RESET!");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 586, -1, 42));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\rrrr.jpg")); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, -1, 500));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\gg.jpg")); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-820, -240, 2990, 1370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int p1 = Integer.parseInt(jTextField1.getText());
        int p2 = Integer.parseInt(jTextField2.getText());
        if ((p1 < 1 || p1 > 3)||(p2 < 1 || p2 > 3)){
            JOptionPane.showMessageDialog(null, "Invalid input values for players", "RPS", JOptionPane.ERROR_MESSAGE);
        }
    
        else if(p1==p2){
            jTextField13.setText("DRAW");
        }
        if (p1 == p2) {
            jTextField13.setText("DRAW");
        } else if ((p1 == 1 && p2 == 3) || (p1 == 2 && p2 == 1) || (p1 == 3 && p2 == 2)) {
            jTextField13.setText("PLAYER 1 WINS");
            int a = Integer.parseInt(jTextField12.getText());
            
            int lives = a - 1;
            jTextField12.setText(""+lives);
            if(a<=1){
                int c = Integer.parseInt(jTextField12.getText());
                int b = Integer.parseInt(jTextField11.getText());
                JOptionPane.showMessageDialog(null, "PLAYER 1: "+b + " and " +" PLAYER 2: " + c +
                        " PRESS RESET BUTTON TO REMATCH ", "PLAYER 1 WINNER!", JOptionPane.OK_OPTION);
            }
        } else if ((p1 == 3 && p2 == 1) || (p1 == 1 && p2 == 2) || (p1 == 2 && p2 == 3)) {
            jTextField13.setText("PLAYER 2 WINS");
            int a = Integer.parseInt(jTextField11.getText());
            
            int lives = a - 1;
            jTextField11.setText(""+lives);
            if(a<=1){
                int c = Integer.parseInt(jTextField12.getText());
                int b = Integer.parseInt(jTextField11.getText());
                JOptionPane.showMessageDialog(null, "PLAYER 1: "+b + " and " +" PLAYER 2: " + c +
                        " PRESS RESET BUTTON TO REMATCH ", "PLAYER 2 WINNER!", JOptionPane.OK_OPTION);
                
            }
            
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("3");
        jTextField12.setText("3");
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int p1 = Integer.parseInt(jTextField3.getText());
        int p2 = Integer.parseInt(jTextField4.getText());
        if ((p1 < 1 || p1 > 3)||(p2 < 1 || p2 > 3)){
            JOptionPane.showMessageDialog(null, "Invalid input values for players", "RPS", JOptionPane.ERROR_MESSAGE);
        }
    
        else if(p1==p2){
            jTextField14.setText("DRAW");
        }
        if (p1 == p2) {
            jTextField14.setText("DRAW");
        } else if ((p1 == 1 && p2 == 3) || (p1 == 2 && p2 == 1) || (p1 == 3 && p2 == 2)) {
            jTextField14.setText("PLAYER 1 WINS");
            int a = Integer.parseInt(jTextField12.getText());
            
            int lives = a - 1;
            jTextField12.setText(""+lives);
            if(a<=1){
                int c = Integer.parseInt(jTextField12.getText());
                int b = Integer.parseInt(jTextField11.getText());
                JOptionPane.showMessageDialog(null, "PLAYER 1: "+b + " and " +" PLAYER 2: " + c +
                        " PRESS RESET BUTTON TO REMATCH ", "PLAYER 1 WINNER!", JOptionPane.OK_OPTION);
            }
        } else if ((p1 == 3 && p2 == 1) || (p1 == 1 && p2 == 2) || (p1 == 2 && p2 == 3)) {
            jTextField14.setText("PLAYER 2 WINS");
            int a = Integer.parseInt(jTextField11.getText());
            
            int lives = a - 1;
            jTextField11.setText(""+lives);
            if(a<=1){
                int c = Integer.parseInt(jTextField12.getText());
                int b = Integer.parseInt(jTextField11.getText());
                JOptionPane.showMessageDialog(null, "PLAYER 1: "+b + " and " +" PLAYER 2: " + c +
                        " PRESS RESET BUTTON TO REMATCH ", "PLAYER 2 WINNER!", JOptionPane.OK_OPTION);
                
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int p1 = Integer.parseInt(jTextField5.getText());
        int p2 = Integer.parseInt(jTextField6.getText());
        if ((p1 < 1 || p1 > 3)||(p2 < 1 || p2 > 3)){
            JOptionPane.showMessageDialog(null, "Invalid input values for players", "RPS", JOptionPane.ERROR_MESSAGE);
        }
    
        else if(p1==p2){
            jTextField15.setText("DRAW");
        }
        if (p1 == p2) {
            jTextField15.setText("DRAW");
        } else if ((p1 == 1 && p2 == 3) || (p1 == 2 && p2 == 1) || (p1 == 3 && p2 == 2)) {
            jTextField15.setText("PLAYER 1 WINS");
            int a = Integer.parseInt(jTextField12.getText());
            
            int lives = a - 1;
            jTextField12.setText(""+lives);
            if(a<=1){
                int c = Integer.parseInt(jTextField12.getText());
                int b = Integer.parseInt(jTextField11.getText());
                JOptionPane.showMessageDialog(null, "PLAYER 1: "+b + " and " +" PLAYER 2: " + c +
                        " PRESS RESET BUTTON TO REMATCH ", "PLAYER 1 WINNER!", JOptionPane.OK_OPTION);
            }
        } else if ((p1 == 3 && p2 == 1) || (p1 == 1 && p2 == 2) || (p1 == 2 && p2 == 3)) {
            jTextField15.setText("PLAYER 2 WINS");
            int a = Integer.parseInt(jTextField11.getText());
            
            int lives = a - 1;
            jTextField11.setText(""+lives);
            if(a<=1){
                int c = Integer.parseInt(jTextField12.getText());
                int b = Integer.parseInt(jTextField11.getText());
                JOptionPane.showMessageDialog(null, "PLAYER 1: "+b + " and " +" PLAYER 2: " + c +
                        " PRESS RESET BUTTON TO REMATCH ", "PLAYER 2 WINNER!", JOptionPane.OK_OPTION);
                
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int p1 = Integer.parseInt(jTextField7.getText());
        int p2 = Integer.parseInt(jTextField8.getText());
        if ((p1 < 1 || p1 > 3)||(p2 < 1 || p2 > 3)){
            JOptionPane.showMessageDialog(null, "Invalid input values for players", "RPS", JOptionPane.ERROR_MESSAGE);
        }
    
        else if(p1==p2){
            jTextField16.setText("DRAW");
        }
        if (p1 == p2) {
            jTextField16.setText("DRAW");
        } else if ((p1 == 1 && p2 == 3) || (p1 == 2 && p2 == 1) || (p1 == 3 && p2 == 2)) {
            jTextField16.setText("PLAYER 1 WINS");
            int a = Integer.parseInt(jTextField12.getText());
            
            int lives = a - 1;
            jTextField12.setText(""+lives);
            if(a<=1){
                int c = Integer.parseInt(jTextField12.getText());
                int b = Integer.parseInt(jTextField11.getText());
                JOptionPane.showMessageDialog(null, "PLAYER 1: "+b + " and " +" PLAYER 2: " + c +
                        " PRESS RESET BUTTON TO REMATCH ", "PLAYER 1 WINNER!", JOptionPane.OK_OPTION);
            }
        } else if ((p1 == 3 && p2 == 1) || (p1 == 1 && p2 == 2) || (p1 == 2 && p2 == 3)) {
            jTextField16.setText("PLAYER 2 WINS");
            int a = Integer.parseInt(jTextField11.getText());
            
            int lives = a - 1;
            jTextField11.setText(""+lives);
            if(a<=1){
                int c = Integer.parseInt(jTextField12.getText());
                int b = Integer.parseInt(jTextField11.getText());
                JOptionPane.showMessageDialog(null, "PLAYER 1: "+b + " and " +" PLAYER 2: " + c +
                        " PRESS RESET BUTTON TO REMATCH ", "PLAYER 2 WINNER!", JOptionPane.OK_OPTION);
                
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int p1 = Integer.parseInt(jTextField9.getText());
        int p2 = Integer.parseInt(jTextField10.getText());
        if ((p1 < 1 || p1 > 3)||(p2 < 1 || p2 > 3)){
            JOptionPane.showMessageDialog(null, "Invalid input values for players", "RPS", JOptionPane.ERROR_MESSAGE);
        }
    
        else if(p1==p2){
            jTextField17.setText("DRAW");
        }
        if (p1 == p2) {
            jTextField17.setText("DRAW");
        } else if ((p1 == 1 && p2 == 3) || (p1 == 2 && p2 == 1) || (p1 == 3 && p2 == 2)) {
            jTextField17.setText("PLAYER 1 WINS");
            int a = Integer.parseInt(jTextField12.getText());
            
            int lives = a - 1;
            jTextField12.setText(""+lives);
            if(a<=1){
                int c = Integer.parseInt(jTextField12.getText());
                int b = Integer.parseInt(jTextField11.getText());
                JOptionPane.showMessageDialog(null, "PLAYER 1: "+b + " and " +" PLAYER 2: " + c +
                        " PRESS RESET BUTTON TO REMATCH ", "PLAYER 1 WINNER!", JOptionPane.OK_OPTION);
            }
        } else if ((p1 == 3 && p2 == 1) || (p1 == 1 && p2 == 2) || (p1 == 2 && p2 == 3)) {
            jTextField17.setText("PLAYER 2 WINS");
            int a = Integer.parseInt(jTextField11.getText());
            
            int lives = a - 1;
            jTextField11.setText(""+lives);
            if(a<=1){
                int c = Integer.parseInt(jTextField12.getText());
                int b = Integer.parseInt(jTextField11.getText());
                JOptionPane.showMessageDialog(null, "PLAYER 1: "+b + " and " +" PLAYER 2: " + c +
                        " PRESS RESET BUTTON TO REMATCH ", "PLAYER 2 WINNER!", JOptionPane.OK_OPTION);
            }
           
            
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(r5r.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(r5r.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(r5r.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(r5r.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new r5r().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
